services:
  postgres:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
